config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'dashboard/user', to: 'pages#users', as: :pages_user
  get 'dashboard/admin', to: 'pages#admin', as: :pages_admin

  devise_for :admin, controllers: {
    sessions: 'admin/sessions'
  }

  devise_for :users,  controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  get 'admin/new trader', to: 'pages#new_user', as: :new_user
  post 'admin/create trader', to: 'pages#create_user', as: :create_user

  get 'admin/edit_user/:id', to: 'pages#edit_user', as: :edit_user
  patch 'admin/update_user/:id', to: 'pages#update_user', as: :update_user
  get 'admin/show_user/:id', to: 'pages#show_user', as: :show_user

  post '/dashboard/user', to: 'pages#users'
  get '/market', to: 'pages#market', as: :market

  get '/transaction/buy', to: 'transactions#buy_transaction', as: :buy_transaction
  post '/transaction/buy', to: 'transactions#buy', as: :buy
  get '/transaction/sell', to: 'transactions#sell_transaction', as: :sell_transaction
  post '/transaction/sell', to: 'transactions#sell', as: :sell


  get '/profile', to: 'stocks#profile', as: :profile
  get '/profile/cashin', to: 'stocks#new_deposit', as: :deposit_transaction
  patch '/profile/cashin', to: 'stocks#deposit', as: :deposit


end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :user
  validates :total_share, numericality: { greater_than_or_equal_to: 0 }

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
    
  def profile
    @stocks = current_user.stocks.order(total_share: :desc )
    @transactions = current_user.transactions.order(created_at: :desc )
    @clients = clients
  
  end
  
  

    def new_deposit
        @user = current_user
    end

    def deposit
        @user = current_user
        new_balance = @user.balance + transaction_params[:amount].to_d
        if @user.update(balance: new_balance)
          redirect_to profile_path, notice: 'Balance updated successfully'
        else
          redirect_to profile_path, alert: 'Unsuccessful Deposit'
        end
    end

    private

    def transaction_params
    params.require(:user).permit(:amount)
    end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_deposit.html.erb
<%= form_with(model: current_user, url: deposit_path, data: { turbo: false }, class: "h-[30vh] w-full flex flex-col gap-[3rem]") do |form| %>
  <%= form.text_field :amount, placeholder: "Amount", class: "text-black rounded-md" %>
  <div class="flex flex-row w-full justify-evenly h-[10vh]">
    <%= form.submit "Deposit",class: "bg-green-700 h-[5vh] w-[30%] rounded-md", id: "submit-deposit" %>
    <%= link_to "Cancel", profile_path, data: {
        controller: "modals",
        action: "modals#close"
      }, class: "bg-blue-700 h-[5vh] w-[30%] rounded-md center-item" %>
  </div>
</div>
<% end %>

app/views/stocks/_stock_list.html.erb
<table class="w-full border text-center">
  <thead>
    <tr>
      <th class="border">Name</th>
      <th class="border">Total Share</th>
      <th class="border">Average Price</th>
      <th class="border">Transaction Cost</th>
      <th class="border">Current Value</th>
      <th class="border">Profit/Loss</th>
    </tr>
  </thead>
  <% if @stocks.empty? || @transactions.empty? %>
    <tbody></tbody>
  <% else %>
    <% @stocks.each do |s| %>
      <tbody>
        <tr>
            <td class="center-item flex-col border border-gray-700"><%= s.stock_symbol %>
            <% company = @clients.company(s.stock_symbol)%>
            <span class="text-[0.7rem] text-gray-500"><%= company.company_name%></span></td>
            <td class="border border-gray-700 "><%= s.total_share %></td>
            <% average = @transactions.where(stock_name: s.stock_symbol).average(:price)%>
            <td class="border border-gray-700 "><%= number_to_currency(average, precision: 2) %> per share</td>
            <% total_cost = average * s.total_share%>
            <td class="border border-gray-700 "><%= number_to_currency(total_cost, precision: 2) %></td>
            <% current_value = s.total_share * @clients.price(s.stock_symbol)%>
            <td class="border border-gray-700 "><%= number_to_currency(current_value, precision: 2) %></td>
            <% if current_value > total_cost.to_f %>
              <td class="text-green-600 border border-gray-700">Profit↑</td>
            <% else %>
              <td class="text-red-600 border border-gray-700">Loss↓</td>
            <% end %>
          
            
        </tr>
      </tbody>
    <% end %>
  <% end %>
</table>

app/views/stocks/_transaction_history.html.erb
<table class="w-full border text-center">
        <thead>
          <tr>
            <th class="border ">Name</th>
            <th class="border ">Share</th>
            <th class="border ">Price</th>
            <th class="border ">Type</th>
            <th class="border ">Amount</th>
            <th class="border ">Time</th>
          </tr>
        </thead>
        <% if @transactions.empty? %>
          <tbody></tbody>
        <% else %>
          <% @transactions.each do |t| %>
            <tbody>
              <tr>
                <td class="border border-gray-700 "><%= t.stock_name %></td>
                <td class="border border-gray-700 "><%= t.share %></td>
                <td class="border border-gray-700 "><%=  number_to_currency(t.price, precision: 2) %></td>
                <% if t.is_buy == true %>
                  <td class="border border-gray-700 text-green-700">Buy</td>
                <% else %>
                  <td class="border border-gray-700 text-red-700">Sell</td>
                <% end %>
                <td class="border border-gray-700 "><%= number_to_currency(t.share * t.price, precision: 2) %></td>
                 <td class="border border-gray-700 w-1/5 py-2"><%= t.created_at.strftime("%a, %b %d, %Y %I:%M %p") %></td>
              </tr>
            </tbody>
          <% end %>
        <% end %>
      </table>

app/views/stocks/new_deposit.html.erb
<%= turbo_frame_tag "modal" do%>
<div class="modal border bg-opacity-25 backdrop-filter backdrop-blur-lg p-8 rounded-2xl shadow-lg text-white w-[20%] h-[40vh] flex flex-col center-item overflow-hidden ">
<h1 class="uppercase text-[1.5rem] font-bold">Deposit</h1>
<br>
<%= render 'stocks/deposit' %>

</div>

<% end %>

app/views/stocks/profile.html.erb
<div class="absolute top-0 left-0 w-full h-full -z-10 overflow-hidden">
  <img class="full-size blur-md" src="<%= image_path('background.jpg') %>" alt="background image">
</div>
<div class=" w-full h-screen flex flex-col gap-[5rem] items-center overflow-auto scroll">
  <!-- #navbar -->
  <div class=" flex justify-between w-full text-white fixed z-10 primary-color border border-gray-700">
   <%= render 'pages/user/navbar' %>
  </div>
  <!-- #user-info -->
  <div class=" max-w-[90%] min-w-[90%] text-white flex flex-col gap-[4rem] mt-[5rem] ">
    <div class="w-full h-[50vh] border border-gray-700 center-item flex-row primary-color rounded-lg">
      <div class=" w-[30%] h-[50vh] center-item">
        <%= image_tag 'trader-img', class: "rounded-full w-[70%] h-[40vh]"%>
      </div>
      <div class="w-[70%] h-[50vh] flex justify-center flex-col p-[1rem] gap-2">
        <h1 class="text-[2rem] capitalize font-bold "> 👋 Hi! <%= current_user.email.split("@")[0]%></h1>
        <div class="w-[40%] flex flex-row justify-between">
          <%= link_to "Edit Profile", edit_user_registration_path , class:"block",  data: { turbo_frame: "modal"}, class:"w-[40%] h-[5vh] center-item bg-blue-700 font-bold rounded-md hover:bg-blue-500 truncate" %>
          <%= link_to "Deposit", deposit_transaction_path , class:"block",  data: { turbo_frame: "modal"}, class:"w-[40%] h-[5vh] center-item bg-blue-700 font-bold rounded-md hover:bg-blue-500 truncate" %>
        </div>
        <div class="flex flex-row h-[20vh] items-center gap-[3rem] ">
          <div class=" h-[14vh] w-[25%] rounded-md flex flex-col justify-center p-4 bg-orange-500 ">
            <h1 class="font-bold truncate text-[1rem] text-gray-300">Current Balance 💵</h1>
            <h1 class="text-[2.3rem] font-bold"><%= number_to_currency(current_user.balance, precision: 2) %></h1>
          </div>
          <% sum_values = @stocks.map { |s| s.total_share * @clients.price(s.stock_symbol)}.sum  %>
          <div class=" h-[14vh] w-[25%] rounded-md flex flex-col justify-center p-4 bg-blue-500 ">
            <h1 class="font-bold truncate text-[1rem] text-gray-300">Portfolio Value</h1>
            <h1 class="text-[2.3rem] font-bold"><%= number_to_currency(current_user.balance + sum_values , precision: 2) %> </h1>
          </div>
        </div>
      </div>
    </div>
    <!-- #stocklist -->
    <div class="w-full max-h-[100vh] border border-gray-700 p-5 overflow-auto scroll flex flex-col gap-[1rem] primary-color rounded-lg">
      <h1 class="text-[1.5rem] font-semibold uppercase">Stocks Portfolio</h1>
      <%= render 'stocks/stock_list' %>
    </div>
    <!-- #transaction list -->
    <div class="w-full max-h-[60vh] border border-gray-700  p-5 flex flex-col gap-[1rem] mb-[5rem] primary-color rounded-lg">
      <h1 class="text-[1.5rem] font-semibold uppercase">Transaction History</h1>
      <div class="max-h-[50vh] overflow-auto scroll">
        <%= render 'stocks/transaction_history' %>
      </div>
    </div>
  </div>
</div>