config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'dashboard/user', to: 'pages#users', as: :pages_user
  get 'dashboard/admin', to: 'pages#admin', as: :pages_admin

  devise_for :admin, controllers: {
    sessions: 'admin/sessions'
  }

  devise_for :users,  controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  get 'admin/new trader', to: 'pages#new_user', as: :new_user
  post 'admin/create trader', to: 'pages#create_user', as: :create_user

  get 'admin/edit_user/:id', to: 'pages#edit_user', as: :edit_user
  patch 'admin/update_user/:id', to: 'pages#update_user', as: :update_user
  get 'admin/show_user/:id', to: 'pages#show_user', as: :show_user

  post '/dashboard/user', to: 'pages#users'
  get '/market', to: 'pages#market', as: :market

  get '/transaction/buy', to: 'transactions#buy_transaction', as: :buy_transaction
  post '/transaction/buy', to: 'transactions#buy', as: :buy
  get '/transaction/sell', to: 'transactions#sell_transaction', as: :sell_transaction
  post '/transaction/sell', to: 'transactions#sell', as: :sell


  get '/profile', to: 'stocks#profile', as: :profile
  get '/profile/cashin', to: 'stocks#new_deposit', as: :deposit_transaction
  patch '/profile/cashin', to: 'stocks#deposit', as: :deposit


end

app/views/pages/edit_user.html.erb
<%= turbo_frame_tag "modal" do%>

<div class="h-1/3 w-1/3 font-thin text-white fixed z-[1] -translate-x-2/4 -translate-y-2/4 overflow-auto bg-[rgba(0,0,0,0.797)] shadow-[0_0_10px_0_rgba(0,0,0,0.2),0_5px_10px_0_rgba(0,0,0,0.19)] p-[2em] rounded-[5px] left-2/4 top-2/4">

<h1>Edit User</h1>
   <br>
<%= form_with(model: @user, url: update_user_path(@user), method: :patch, local: true, data: { turbo: false }) do |form| %>
 <div>
   <%= form.label :email %>
   <%= form.text_field :email, class: "bg-transparent border-x=transparent" %>
   <br>
      <br>
   <% if @user.is_approved? %>
      User is approved for trading.
   <% elsif @user.confirmed? && !@user.is_approved %>
      <span>Approved User for Trading</span>
      <%= form.check_box :is_approved %>
   <% else %>
      User haven't confirmed his/her account yet.
   <% end %>
 </div>

 <%= form.submit "Update User",class: "absolute left-10 bottom-10 bg-transparent text-xs text-[white] rounded cursor-pointer float-right no-underline px-2 py-1 border-[none] hover:bg-gray-500" %>
<% end %>

<%= link_to "Cancel", pages_user_path, data: {
    controller: "modals",
    action: "modals#close"
    }, class: "absolute right-10 bottom-10 bg-transparent text-xs text-[white] rounded cursor-pointer float-right no-underline px-2 py-1 border-[none] hover:bg-gray-500" %>
</div>

<% end %>

app/views/pages/home.html.erb
<div class= "center-item flex-col full-size text-white">

<div class="absolute top-0 left-0 w-full h-full -z-10 overflow-hidden">
   <img class="full-size" src="<%= image_path('background.jpg') %>" alt="background image">
</div>

<span class="absolute left-16 top-16 flex flex-row justify-center items-center text-3xl pt-5"><img class="w-10 h-10" src="<%= image_path('Logos/logo-white-256x256.png') %>" alt="logo white">TradeMaster</span>

<div>
  <button class="absolute group right-20 top-20">
    <div class="relative flex items-center justify-center rounded-full w-[50px] h-[50px] transform transition-all bg-transparent ring-0 ring-gray-300 hover:ring-8 group-focus:ring-4 ring-opacity-30 duration-200 shadow-md">
    <div class="flex flex-col justify-between w-[20px] h-[20px] transform transition-all duration-300 group-focus:-rotate-[45deg] origin-center">
    <div class="bg-white h-[2px] w-1/2 rounded transform transition-all duration-300 group-focus:-rotate-90 group-focus:h-[1px] origin-right delay-75 group-focus:-translate-y-[1px]"></div>
    <div class="bg-white h-[1px] rounded"></div>
    <div class="bg-white h-[2px] w-1/2 rounded self-end transform transition-all duration-300 group-focus:-rotate-90 group-focus:h-[1px] origin-left delay-75 group-focus:translate-y-[1px]"></div>
    </div>
    </div>
  </button>
</div>

<div class="animate-[fadeIn_2s_ease-in-out]">
<div class="absolute left-16 top-86 text-2xl">
    <span class="font-medium font-sans">Trade Smart, Trade Fast</span>
    <p class="font-thin pt-5 text-gray-100">Whether you're a seasoned trader or just starting out,<br> we've got the tools and resources to help you succeed. </p>
</div>
<span class="absolute left-16 bottom-80 hover:text-gray-400 hover:cursor-pointer font-medium font-sans">Learn More</span>
</div>

<span class="absolute right-20 top-86 text-gray-300"><%= Date.current.strftime("%d / %m") %></span>

<div class="flex p-20">

    <%= link_to "SIGN IN", new_user_session_path, class: "absolute left-20 bottom-10 font-thin hover:text-gray-300 " %>
    <%= link_to "SIGN UP", new_user_registration_path, class: "absolute left-40 bottom-10 font-thin hover:text-gray-300 " %>


    <%= link_to "Admin", new_admin_session_path, class: "absolute right-20 bottom-10 font-thin text-black hover:text-white" %>

</div>
</div>

app/views/pages/market.html.erb
<div class=" h-screen flex flex-col  relative overflow-auto scroll gap-[5rem] items-center ">
  <div class="w-full h-[5vh] fixed top-0 bg-opacity-25 backdrop-filter backdrop-blur-lg p-8 shadow-lg text-white flex items-center justify-between opacity-0 transition-opacity duration-300 hover-hidden "><%= link_to pages_user_path, class:"text-[2.5rem]" do %><i class="fa-sharp fa-solid fa-left-long"></i>
    <% end %>
    <h1 class="font-bold text-4xl flex flex-row"> <img class="w-10 h-10" src="<%= image_path('Logos/logo-white-256x256.png') %>" alt="logo white">TradeMaster</h1>
  </div>
  
  <div class="w-full min-h-screen">
    <div class="tradingview-widget-container"></div>
    <div class="tradingview-widget-container__widget"></div>
    <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-stock-heatmap.js" async>
      {
          "exchanges": [],
          "dataSource": "SPX500",
          "grouping": "no_group",
          "blockSize": "market_cap_basic",
          "blockColor": "Perf.YTD",
          "locale": "en",
          "symbolUrl": "",
          "colorTheme": "dark",
          "hasTopBar": false,
          "isDataSetEnabled": false,
          "isZoomEnabled": true,
          "hasSymbolTooltip": true,
          "width": "100%",
          "height": "100%"
      }
    </script>
  </div>
  <div class="w-[90%] h-[70vh] flex flex-row justify-between">
    <div class="w-[20%] h-[70vh] bg-gray-700">
      <!-- TradingView Widget BEGIN -->
      <div class="tradingview-widget-container">
        <div class="tradingview-widget-container__widget"></div>
        <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-market-overview.js" async>
          {
          "colorTheme": "dark",
          "dateRange": "12M",
          "showChart": true,
          "locale": "en",
          "width": "100%",
          "height": "100%",
          "largeChartUrl": "",
          "isTransparent": true,
          "showSymbolLogo": true,
          "showFloatingTooltip": false,
          "plotLineColorGrowing": "rgba(41, 98, 255, 1)",
          "plotLineColorFalling": "rgba(41, 98, 255, 1)",
          "gridLineColor": "rgba(42, 46, 57, 0)",
          "scaleFontColor": "rgba(134, 137, 147, 1)",
          "belowLineFillColorGrowing": "rgba(41, 98, 255, 0.12)",
          "belowLineFillColorFalling": "rgba(41, 98, 255, 0.12)",
          "belowLineFillColorGrowingBottom": "rgba(41, 98, 255, 0)",
          "belowLineFillColorFallingBottom": "rgba(41, 98, 255, 0)",
          "symbolActiveColor": "rgba(41, 98, 255, 0.12)",
          "tabs": [
            {
              "title": "Indices",
              "symbols": [
                {
                  "s": "FOREXCOM:SPXUSD",
                  "d": "S&P 500 Index"
                },
                {
                  "s": "FOREXCOM:NSXUSD",
                  "d": "US 100 Cash CFD"
                },
                {
                  "s": "FOREXCOM:DJI",
                  "d": "Dow Jones Industrial Average Index"
                },
                {
                  "s": "INDEX:NKY",
                  "d": "Nikkei 225"
                },
                {
                  "s": "INDEX:DEU40",
                  "d": "DAX Index"
                },
                {
                  "s": "FOREXCOM:UKXGBP",
                  "d": "FTSE 100 Index"
                }
              ],
              "originalTitle": "Indices"
            },
            {
              "title": "Futures",
              "symbols": [
                {
                  "s": "CME_MINI:ES1!",
                  "d": "S&P 500"
                },
                {
                  "s": "CME:6E1!",
                  "d": "Euro"
                },
                {
                  "s": "COMEX:GC1!",
                  "d": "Gold"
                },
                {
                  "s": "NYMEX:CL1!",
                  "d": "WTI Crude Oil"
                },
                {
                  "s": "NYMEX:NG1!",
                  "d": "Gas"
                },
                {
                  "s": "CBOT:ZC1!",
                  "d": "Corn"
                }
              ],
              "originalTitle": "Futures"
            },
            {
              "title": "Bonds",
              "symbols": [
                {
                  "s": "CBOT:ZB1!",
                  "d": "T-Bond"
                },
                {
                  "s": "CBOT:UB1!",
                  "d": "Ultra T-Bond"
                },
                {
                  "s": "EUREX:FGBL1!",
                  "d": "Euro Bund"
                },
                {
                  "s": "EUREX:FBTP1!",
                  "d": "Euro BTP"
                },
                {
                  "s": "EUREX:FGBM1!",
                  "d": "Euro BOBL"
                }
              ],
              "originalTitle": "Bonds"
            },
            {
              "title": "Forex",
              "symbols": [
                {
                  "s": "FX:EURUSD",
                  "d": "EUR to USD"
                },
                {
                  "s": "FX:GBPUSD",
                  "d": "GBP to USD"
                },
                {
                  "s": "FX:USDJPY",
                  "d": "USD to JPY"
                },
                {
                  "s": "FX:USDCHF",
                  "d": "USD to CHF"
                },
                {
                  "s": "FX:AUDUSD",
                  "d": "AUD to USD"
                },
                {
                  "s": "FX:USDCAD",
                  "d": "USD to CAD"
                }
              ],
              "originalTitle": "Forex"
            }
          ]
          }
        </script>
      </div>
      <!-- TradingView Widget END -->
    </div>
    <div class="w-[20%] h-[70vh] bg-gray-700">
      <!-- TradingView Widget BEGIN -->
      <div class="tradingview-widget-container">
        <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-timeline.js" async>
          {
          "feedMode": "all_symbols",
          "isTransparent": true,
          "displayMode": "regular",
          "width": "100%",
          "height": "100%",
          "colorTheme": "dark",
          "locale": "en"
          }
        </script>
      </div>
      <!-- TradingView Widget END -->
    </div>
    <div class="w-[45%] h-[70vh] bg-gray-700">
      <!-- TradingView Widget BEGIN -->
      <div class="tradingview-widget-container">
        <div class="tradingview-widget-container__widget"></div>

        <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-screener.js" async>
          {
          "width": "100%",
          "height": "100%",
          "defaultColumn": "overview",
          "defaultScreen": "most_capitalized",
          "market": "america",
          "showToolbar": false,
          "colorTheme": "dark",
          "locale": "en",
          "isTransparent": true
          }
        </script>
      </div>
      <!-- TradingView Widget END -->
    </div>
  </div>
  <div class="w-full"><!-- TradingView Widget BEGIN -->
    <div class="tradingview-widget-container">
      <div class="tradingview-widget-container__widget"></div>
      <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-ticker-tape.js" async>
        {
          "symbols": [
            {
              "description": "Tesla",
              "proName": "NASDAQ:TSLA"
            },
            {
              "description": "Apple Inc",
              "proName": "NASDAQ:AAPL"
            },
            {
              "description": "Nvidia",
              "proName": "NASDAQ:NVDA"
            },
            {
              "description": "Microsoft",
              "proName": "NASDAQ:MSFT"
            },
            {
              "description": "Advanced Micro Devices",
              "proName": "NASDAQ:AMD"
            },
            {
              "description": "Meta",
              "proName": "NASDAQ:META"
            },
            {
              "description": "Netflix",
              "proName": "NASDAQ:NFLX"
            }
          ],
          "showSymbolLogo": true,
          "colorTheme": "dark",
          "isTransparent": false,
          "displayMode": "compact",
          "locale": "en"
        }
      </script>
    </div>
    <!-- TradingView Widget END -->
  </div>
</div>

app/views/pages/new_user.html.erb
<%= turbo_frame_tag "modal" do%>


<div class="h-1/3 w-1/3 font-thin text-white fixed z-[1] -translate-x-2/4 -translate-y-2/4 overflow-auto bg-[rgba(0,0,0,0.797)] shadow-[0_0_10px_0_rgba(0,0,0,0.2),0_5px_10px_0_rgba(0,0,0,0.19)] p-[2em] rounded-[5px] left-2/4 top-2/4">
  <h1>Create New Trader</h1>
  <div class= "flex flex-col justify-center">
    
  <%= form_with(model: @user, url: create_user_path, data: { turbo: false }) do |f| %>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "text-black m-2" %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "text-black m-2" %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "text-black m-2" %>
  </div>

    <%= f.submit "Create User", class: 'absolute left-10 bottom-10 bg-transparent text-xs text-[white] rounded cursor-pointer float-right no-underline px-2 py-1 border-[none] hover:bg-gray-500'%>
  <% end %>
  </div>


  <%= link_to "Cancel", pages_user_path, data: {
        controller: "modals",
        action: "modals#close"
      }, class: "absolute right-10 bottom-10 bg-transparent text-xs text-[white] rounded cursor-pointer float-right no-underline px-2 py-1 border-[none] hover:bg-gray-500" %>
</div>
<% end %>

app/views/pages/show_user.html.erb
<%= turbo_frame_tag "modal" do%>

<div class="h-1/3 w-1/3 font-thin text-white fixed z-[1] -translate-x-2/4 -translate-y-2/4 overflow-auto bg-[rgba(0,0,0,0.797)] shadow-[0_0_10px_0_rgba(0,0,0,0.2),0_5px_10px_0_rgba(0,0,0,0.19)] p-[2em] rounded-[5px] left-2/4 top-2/4">
<br>
<p>User ID: <%= @user.id %></p>
<br>
<p>Email: <%= @user.email %></p>
<br>
<p>Balance: <%= @user.balance %></p>
<br>
<p>Member Since: <%= @user.created_at %></p>

<%= link_to "Cancel", pages_user_path, data: {
    controller: "modals",
    action: "modals#close"
    }, class: "absolute right-10 bottom-10 bg-transparent text-xs text-[white] rounded cursor-pointer float-right no-underline px-2 py-1 border-[none] hover:bg-gray-500" %>
</div>

<% end %>

app/views/pages/users.html.erb
<div class="primary-color text-white full-size overflow-hidden relative">
  <!-- #navbar -->
  <div class=" flex justify-between pt-3">
   <%= render 'pages/user/navbar' %>
  </div>
  <!-- #ticker -->
  <div class="w-full h-[5vh]">
    <%= render 'pages/user/ticker' %>
  </div>
  <!-- #middle container -->
  <div class=" min-w-full max-w-full h-[70vh] flex flex-row">

      <!-- #marketlist container -->
    <div class=" w-[25%] h-[70vh] text-[0.8rem] center-item flex-col truncate">
      <%= render 'pages/user/market_list' %>
    </div>
    <!-- #chart container -->
    <div class="h-[70vh] w-[50%]">
      <div class="h-[70vh] w-full center-item">
        <%= render 'pages/user/chart' %>
      </div>
    </div>
    <!-- #transaction container -->
    <div class="border border-gray-700 w-[25%] h-[70vh] center-item flex-col justify-evenly" >
      <div class="h-[10vh] w-full center-item flex flex-col">
        <div id="error-message" class="text-red-500 hidden text-[0.7rem]">Please select a valid option from the list.</div>
        <%= render 'pages/user/search_form' %>
      </div>
      <div class="h-[60vh] w-full center-item justify-evenly flex-col ">
        <% if current_user.is_approved == true && @symbol.present? && @stock_list.include?(@symbol) == true %>
          <div class="w-full ">
            <%= render 'pages/user/stock_info' %>
          </div>
          <div class="w-full flex flex-row justify-evenly"> 
            <div class="w-[40%] h-[8vh] rounded-lg bg-green-700 center-item text-[1.5rem] uppercase hover:bg-green-500">
              <%= link_to 'Buy', buy_transaction_path, data: { turbo_frame: "modal"}, class: "w-full center-item" %></div>
            <div class="w-[40%] h-[8vh] rounded-lg bg-red-700 center-item text-[1.5rem] uppercase hover:bg-red-500">
              <%= link_to 'Sell', sell_transaction_path, data: { turbo_frame: "modal"}, class: "w-full center-item" %>
            </div>
          </div>
        <% elsif current_user.is_approved == true  && @symbol.present? && @stock_list.include?(@symbol) == false %>
          <div class="w-full">
            <%= render 'pages/user/stock_info' %>
          </div>
          <div class="w-[50%] h-[8vh] rounded-lg bg-green-700 center-item text-[1.5rem] uppercase">
            <%= link_to 'Buy', buy_transaction_path, data: { turbo_frame: "modal"}, class: "w-full center-item" %></div>
        <% elsif current_user.is_approved == true && !@symbol.present? %>
          <h1 class="text-center text-gray-500 font-bold text-[1.5rem]">"Select the stock to trade."</h1>
        <% else %>
          <h1 class="text-center text-gray-500 font-bold text-[1.5rem] p-4">"To transact, <br>
            kindly authenticate your account first."</h1>
        <% end %>
      </div>
    </div>
  </div>
  <!-- #transactionlist container -->
  <div class=" max-h-[20vh] max-w-full overflow-auto scroll">
    <%= render 'pages/user/transaction_list' %>
  </div>
</div>