config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'dashboard/user', to: 'pages#users', as: :pages_user
  get 'dashboard/admin', to: 'pages#admin', as: :pages_admin

  devise_for :admin, controllers: {
    sessions: 'admin/sessions'
  }

  devise_for :users,  controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  get 'admin/new trader', to: 'pages#new_user', as: :new_user
  post 'admin/create trader', to: 'pages#create_user', as: :create_user

  get 'admin/edit_user/:id', to: 'pages#edit_user', as: :edit_user
  patch 'admin/update_user/:id', to: 'pages#update_user', as: :update_user
  get 'admin/show_user/:id', to: 'pages#show_user', as: :show_user

  post '/dashboard/user', to: 'pages#users'
  get '/market', to: 'pages#market', as: :market

  get '/transaction/buy', to: 'transactions#buy_transaction', as: :buy_transaction
  post '/transaction/buy', to: 'transactions#buy', as: :buy
  get '/transaction/sell', to: 'transactions#sell_transaction', as: :sell_transaction
  post '/transaction/sell', to: 'transactions#sell', as: :sell


  get '/profile', to: 'stocks#profile', as: :profile
  get '/profile/cashin', to: 'stocks#new_deposit', as: :deposit_transaction
  patch '/profile/cashin', to: 'stocks#deposit', as: :deposit


end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

def buy_transaction
    @transaction = current_user.transactions.new()
    @clients = clients
    @symbol = cookies[:data_symbol]
    if @symbol.present?
        @price_data = @clients.price(@symbol)
    end   

end

def sell_transaction
    @transaction = current_user.transactions.new()
    @clients = clients
    @stock_list = current_user.stocks.pluck(:stock_symbol).join(",")
    @symbol = cookies[:data_symbol]
    if @symbol.present?
        @price_data = @clients.price(@symbol)
        @stocks = current_user.stocks.find_by(stock_symbol: @symbol)
    end 
end


def buy
    Transaction.buy(current_user, transaction_params)
    if transaction_params[:share].to_i > 0
    flash[:notice] = "Successful Transaction."
    end
    redirect_to pages_user_path
rescue ActiveRecord::RecordInvalid
    flash[:alert] = "Please check your Balance or input share to process."
    redirect_to pages_user_path
end
  

def sell
    Transaction.sell(current_user, transaction_params)
    if transaction_params[:share].to_i > 0
    flash[:notice] = "Successful Transaction."
    end
    redirect_to pages_user_path
rescue ActiveRecord::RecordInvalid
    flash[:alert] = "There is an error in this transaction. kindly check your inputs."
    redirect_to pages_user_path
end

private

def transaction_params
    params.require(:transaction).permit(:price, :share, :amount, :is_buy, :stock_name, :amount)
end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_buy_form.html.erb
<%= form_with(model: @transaction, url: buy_path, data: { turbo: false }, class: "h-[40vh] flex flex-col justify-between") do |form| %>
  <%= form.text_field :stock_name, placeholder: "stock", value: @symbol, class: "text-black rounded-md" %>
<div class="bg-white flex flex-row rounded-md px-2 gap-2">
   <%= form.text_field :price, value: @price_data, placeholder: "price", class: "text-black w-[80%] border-none " %> <span class="text-green-700 truncate center-item">USD</span>
</div>
 
  <%= form.text_field :share, placeholder: "share amount", class: "text-black rounded-md" %>

  <%= form.hidden_field :is_buy, value: "true"%>
 <div class="flex flex-row justify-between">
   <%= form.submit "Buy", class: "bg-green-700 h-[5vh] w-[30%] rounded-md cursor-pointer", id: "buy-submit"  %>
  <%= link_to "Cancel", pages_user_path, data: {
        controller: "modals",
        action: "modals#close"
      }, class: "bg-blue-700 h-[5vh] w-[30%] rounded-md center-item" %>
 </div>
 
<% end %>

app/views/transactions/_sell_form.html.erb
<%= form_with(model: @transaction, url: sell_path, data: { turbo: false }, class: "h-[45vh] flex flex-col justify-between") do |form| %>

  <h1 class="text-center text-green-500 font-bold uppercase">Remaining Share : <%= @stocks.total_share%></h1>
    <%= form.text_field :stock_name, placeholder: "stock", value: @symbol, class: "text-black rounded-md" %>
<div class="bg-white flex flex-row rounded-md px-2 gap-2">
   <%= form.text_field :price, value: @price_data, placeholder: "price", class: "text-black w-[80%] border-none" %> <span class="text-green-700 center-item truncate">USD</span>
</div>
 
  <%= form.text_field :share, placeholder: "share amount", class: "text-black rounded-md" %>

  <%= form.hidden_field :is_buy, value: "false"%>
 <div class="flex flex-row justify-between">
   <%= form.submit "Sell", class: "bg-red-700 h-[5vh] w-[30%] rounded-md cursor-pointer", id: "sell-submit" %>
  <%= link_to "Cancel", pages_user_path, data: {
        controller: "modals",
        action: "modals#close"
      }, class: "bg-blue-700 h-[5vh] w-[30%] rounded-md center-item" %>
 </div>
 
<% end %>

app/views/transactions/buy_transaction.html.erb
<%= turbo_frame_tag "modal" do%>
<div class="modal primary-color text-white w-[20%] h-[45vh] flex flex-col justify-evenly overflow-hidden gap-4">
    <h1>Balance: <%= number_to_currency(current_user.balance, precision: 2)%></h1>
<%= render 'buy_form' %>
</div>
<% end %>

app/views/transactions/sell_transaction.html.erb
<%= turbo_frame_tag "modal" do%>
  <div class="modal primary-color text-white w-[20%] h-[45vh] flex flex-col justify-evenly overflow-hidden">
    <%= render 'sell_form' %>
  </div>
<% end %>